### ISSUE TITLE
Error RSCompact

### ISSUE THREAD

**Issue by zBoringDrop** [ClassicTowny/RealisticSwimmingCompat#1]
Hi, now, in my server happens this, can you fix?
https://pastebin.com/LdejW3NF

**Comment by DrkMatr1984** [comment]
Hmm, the pastebin expired, can u paste again?

**Comment by zBoringDrop** [comment]
Oh, i can't :(
I deleted all my log yesterday..

**Comment by zBoringDrop** [comment]
Oh, i can't :(
I deleted all my log yesterday..

**Comment by DrkMatr1984** [comment]
Awww, well, if you get the error again, link me again and I'll fix it :)

**Comment by zBoringDrop** [comment]
There is this:
https://pastebin.com/Y5kk6HEE

**Comment by DrkMatr1984** [comment]
Should be fixed now here:
https://github.com/ClassicTowny/RealisticSwimmingCompat/releases/tag/0.11

**Comment by zBoringDrop** [comment]
Thanks ;)
